#!/usr/bin/env python3

#author : Simran Kohli simran.kohli@colorado.edu
#name : NMtcpdump.py
#purpose : A script to parse and extract MAC
#date : 2018.02.23
#version : 1.2

import os
import sys
from scapy.all import *

fileName = 'lab5obj2.pcap' # replace with required .pcap file

def checkFile(fileName):                # checks to see if file exists
    print("File name is: " + fileName)
    if os.path.isfile(fileName):
        print("File exists")
    else:
        print("File not found")
        sys.exit()

def read_file(fileName):                # reads the files to extract MAC
    try:                                # try and except block for scapy module
        pkts_list = rdpcap(fileName)

        n = len(pkts_list)
        num = 0

        print("No of pkts in file is", n)

        #while num < n:
        while num < 3:
            #print(pkts_list[num].summary())
            if 'ICMPv6 Echo Request' in pkts_list[num].summary():
                # determines the src IP
                a = pkts_list[num]['IPv6'].src
                #print(a)
                print("This is the source IP",a, "for packet no:", num)
                parts = a.split(':')
                #print(parts[4],parts[5],parts[6],parts[7])
                print(parts[4].replace('e','c'),".0",parts[5].replace('f',''),parts[6].replace('fe',''),".00",parts[7])            #print(type(parts[4]))
                #print(pkts_list[num]['IPv6'].data)
                # determines the dst IP
                #print("This is the destination IP", pkts_list[num]['IPv6'].dst, "for packet no:", num)
                #print whole packet
                #print("This is data for packet no.:", num)
                #print(pkts_list[num]['IPv6'].show())
                #determines the src MAC
                #print("This is the Src MAC", pkts_list[num]['Ethernet'].src, "for packet no.:", num)
                #determines the dst MAC
                #print("This is the Src MAC", pkts_list[num]['Ethernet'].dst, "for packet no.:", num)
            num = num + 1
        sys.exit()

    except ImportError:
        print("Scapy module not found")
        sys.exit()

checkFile(fileName)
read_file(fileName)
